str = "i aM IrOnmAn"
str0 = "i\taM\tIrOnmAn"
str1 = "ṅśṅḍḥñṭḍ"
str2 = "8696590494"
str3 = "1.5 3.6"
print(str.capitalize())
print(str.casefold())
print(str.center(20, "-"))
print(str.count("n"))
print(str.count("nm"))
print(str1.encode("ascii", "ignore"))
print(str1.encode("ascii", "xmlcharrefreplace"))
print(str1.encode("ascii", "backslashreplace"))
print(str.endswith("an"))
print(str.endswith("An"))
print(str0.expandtabs(tabsize=15))
print(str.find("nm"))
print("{} and{}".format("Apple", " Banana"))
print("{1} and{0}".format(" Apple", "Banana"))
print("{lunch} and{dinner}".format(lunch="Peas", dinner=" Beans"))
lunch = {"Food": "Pizza", "Drink": "Wine"}
print("Lunch: {Food},{Drink}".format_map(lunch))
print(str.index("m"))
print(str.isalnum())
print(str1.isalnum())
print(str2.isalnum())
print(str.isalpha())
print(str1.isalpha())
print(str2.isalpha())
print(str.isdecimal())
print(str1.isdecimal())
print(str2.isdecimal())
print(str.isdigit())
print(str1.isdigit())
print(str2.isdigit())
print(str3.isdigit())
print(str.isidentifier())
print(str1.isidentifier())
print(str2.isidentifier())
print(str3.isidentifier())
print(str.islower())
print(str.isupper())
print(str.isnumeric())
print(str1.isnumeric())
print(str2.isnumeric())
print(str3.isnumeric())
print(str.isprintable())
print(str0.isprintable())
print(str.isspace())
print(str0.isspace())
print(str.istitle())
a = "-"
print(a.join("123"))
print(str.ljust(16, "_"))
print(str.lower())
print(str.upper())
print(str.lstrip(), "!")
frm = "SecretCode"
to = "8203670540"
trans_table = str.maketrans(frm, to)
sec_code = "SecretCode".translate(trans_table)
print(sec_code)
print(str.partition('-'))


